name: Move.it app

on:
  push:
    branches: *-feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Create tag
      run: |
        LAST_TAG=$(git describe --tags --match "build-*" --abbrev=0 2>/dev/null || echo "build-0.0.0")
        LAST_VERSION=$(echo $LAST_TAG | sed 's/build-//')
        IFS='.' read -r -a VERSION_ARRAY <<< "$LAST_VERSION"
        MAJOR=${VERSION_ARRAY[0]}
        MINOR=${VERSION_ARRAY[1]}
        PATCH=${VERSION_ARRAY[2]}
        NEXT_PATCH=$((PATCH + 1))
        NEXT_VERSION="$MAJOR.$MINOR.$NEXT_PATCH"
        TAG_NAME="build-$NEXT_VERSION"
        git tag $TAG_NAME
        git push --tags